# Generated by Django 2.1.7 on 2019-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='pictures')),
                ('video', models.FileField(upload_to='pictures')),
                ('branch_choice', models.CharField(choices=[('CSE', 'computer '), ('ECE', 'electrical '), ('ME', 'mechanical'), ('CIVIL', 'civil'), ('EEE', 'electronics')], default=None, max_length=2)),
            ],
        ),
    ]
