# Generated by Django 2.1.7 on 2019-06-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190607_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='photo',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
