# Generated by Django 2.1.7 on 2019-06-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20190608_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
