# Generated by Django 2.1.7 on 2019-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190608_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
